bow_batch_size: 100
bow_json_file: $(env HYDRA_LOGS)/cubicles_load/$(arg robot_name)/$(arg robot_name)_bow_vectors.json
vlc_json_file: $(env HYDRA_LOGS)/cubicles_load/$(arg robot_name)/$(arg robot_name)_vlc_frames.json
bow_skip_num: 1
comm_sleep_time: 1
load_session: true
robot_id: $(env PREV_ID)
robot_name: $(arg robot_name)
vlc_batch_size: 10
